version: '3'
services: 
    db:
        image: mysql:5.7.16
        container_name: db
        environment:
         MYSQL_ROOT_PASSWORD: sheep
         MYSQL_DATABASE: tracker
        ports:
            - "8000:3306" 
        networks:
            - back
        volumes:
            - my-datavolume:/var/lib/mysql
    web:  
        build: ./backend
        container_name: web
        ports:
            - "8080:8080"
        networks:
            - back
        depends_on:
            - db
    front:
        build: ./frontend
        container_name: front
        ports:
            - "3000:3000"
networks:
    back:
        driver: bridge

volumes:
  my-datavolume: